FROM node:10-alpine as builder
WORKDIR /usr/src/app
COPY package*.json /app/
RUN npm i

FROM node:10-alpine as delivery
WORKDIR /usr/src/app
ENV PATH=/app/node_modules/.bin:$PATH
COPY --from=builder /usr/src/app/node_modules/ /usr/src/app/node_modules/
COPY . .
CMD ["node", "server.js"]
